In [2]:
import numpy as np
arr1 = np.array([1,2,3,4])
print('创建的数组是：',arr1)

创建的数组是： [1 2 3 4]


In [3]:
arr2 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print('创建的二维数组是：\n',arr2)

创建的二维数组是：
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [4]:
print('数组的维度为：',arr2.shape)

数组的维度为： (3, 4)


In [5]:
print('数组类型为：',arr2.dtype)

数组类型为： int64


In [6]:
print('数组元素个数：',arr2.size)

数组元素个数： 12


In [7]:
print('数组每个元素的大小:',arr2.itemsize)

数组每个元素的大小: 8


In [8]:
print('数据的维数：',arr2.ndim)

数据的维数： 2


In [9]:
print('数据1的维数：',arr1.ndim)

数据1的维数： 1


In [10]:
print('数据1的维度：',arr1.shape)

数据1的维度： (4,)


In [11]:
print('数据1的元素个数',arr1.size)

数据1的元素个数 4


In [12]:
print('数据1的元素类型：',arr1.dtype)
print('数据1的元素大小：',arr1.itemsize)

数据1的元素类型： int64
数据1的元素大小： 8


In [13]:
arr2.shape=4,3
print('修改后的arr2\n',arr2)

修改后的arr2
 [[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


NumPy中函数的使用

In [14]:
print('使用arange函数创建的数组为：\n',np.arange(0,1,0.1))

使用arange函数创建的数组为：
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [15]:
print('使用linspace函数创建的数组为：\n',np.linspace(0,1,12))

使用linspace函数创建的数组为：
 [0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [16]:
print('使用logspace函数创建的数组为：\n',np.logspace(0,2,20))

使用logspace函数创建的数组为：
 [  1.           1.27427499   1.62377674   2.06913808   2.6366509
   3.35981829   4.2813324    5.45559478   6.95192796   8.8586679
  11.28837892  14.38449888  18.32980711  23.35721469  29.76351442
  37.92690191  48.32930239  61.58482111  78.47599704 100.        ]


In [21]:
print('使用zeros函数创建的数组为：\n',np.zeros((2,3)))

使用zeros函数创建的数组为：
 [[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
print('使用eye函数创建的数组为：\n',np.eye(3))

使用eye函数创建的数组为：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
print('使用diag函数创建的数组为：\n',np.diag([1,2,3,4]))

使用diag函数创建的数组为：
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [24]:
print('使用ones函数创建的数组：\n',np.ones((5,3)))

使用ones函数创建的数组：
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
print('转换结果为：',np.float64(42))#整型转换为浮点型

转换结果为： 42.0


In [27]:
print('转换结果为：',np.int8(42.0))#浮点型转换为整型

转换结果为： 42


In [29]:
print('转换结果为：',np.bool(31))#整型转换为布尔型

转换结果为： True


In [30]:
print('转换结果为：',np.bool(0))#整型转换为布尔型

转换结果为： False


In [32]:
print('转换结果为：',np.float(True))#布尔型转换为浮点型

转换结果为： 1.0


In [33]:
print('转换结果为：',np.float(False))#布尔型转换为浮点型

转换结果为： 0.0
